### ISSUE TITLE
Breaks with Python toolchains (Bazel 0.27)

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/tulsi#94]
Bazel 0.27 enables [`--incompatible_use_python_toolchains`](https://github.com/bazelbuild/bazel/issues/7899), which [breaks](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/126#3e8c65c0-6b1f-4f03-b539-9676ae67c35d/1158-1200) tulsi's CI. This flag causes Bazel to actually use the Python version that was decided at analysis time, instead of whatever the system `python` command happens to be.

You likely want to add `python_version = "PY2"` to some targets. If Python 2 targets are used in the host configuration, you'll want to set `--host_force_python=PY2`.

Note that in a [recent rerun](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1009#127a530f-9748-4a58-a0cc-488e1e486966), tulsi fails in CI for an unrelated breakage that masks this one.

**Comment by brandjon** [comment]
@sergiocampama I believe you asked me to notify you about this type of breakage when we last spoke in person.

**Comment by brandjon** [comment]
Ping @DavidGoldman and @ivanhernandez, can you look at this? It affects the current Bazel RC.

**Comment by brandjon** [comment]
The unrelated failures I mentioned were in `TulsiGeneratorIntegrationTests:*`. And the current dominating failure is for #95. So for both reasons, it's not currently possible to observe this failure at head.

Looking again at the error from before, it is definitely a PY2-code-running-in-a-PY3-interpreter error, and the failing action has `bazel-out/host` in the path, so you do need to set `--host_force_python=PY2` in the project bazelrc file. Looks like there isn't one already so you'll have to create it. Then our downstream projects CI should pick it up.

Downstream users of tulsi should also set `--host_force_python=PY2` until such time as they're not depending on any PY2 code in the host configuration. (This issue affects a lot of users but we don't have better alternatives without regressing on PY3-as-default, or Python version checking; or else waiting for the host config to be eliminated entirely.)

**Comment by brandjon** [comment]
Spoke with David, the Python failure appears to be upstream, in rules_apple (tracked in bazelbuild/rules_apple#456).

**Comment by DavidGoldman** [comment]
I believe this should be fixed as of 1cb0527be12

**Comment by brandjon** [comment]
rules_apple is actually still failing in CI, I think because they didn't update their bazelrc. But I guess that doesn't block downstream projects from updating their own bazelrc. [CI looks good](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1030#65dfae8b-1654-4141-bef2-929d21f098af), feel free to close.

**Comment by DavidGoldman** [comment]
Closing as the tests are now passing on CI
